service: bemykeyboardapi
# app and org for use with dashboard.serverless.com
app: bemykeyboardapi
org: th3vanger

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  stage: dev
  region: eu-west-1

functions: # add 4 functions for CRUD
  create:
    handler: handler.create # point to exported create function in handler.js
    events:
      - http:
          path: guides # path will be domain.name.com/dev/guides
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: guides/{id} # path will be domain.name.com/dev/guides/1
          method: get
          cors: true
  getAll:
    handler: handler.getAll # path will be domain.name.com/dev/guides
    events:
     - http:
         path: guides
         method: get
         cors: true
  # update:
  #   handler: handler.update # path will be domain.name.com/dev/guides/1
  #   events:
  #    - http:
  #        path: guides/{id}
  #        method: put
  #        cors: true
  # delete:
  #   handler: handler.delete
  #   events:
  #    - http:
  #        path: guides/{id} # path will be domain.name.com/dev/guides/1
  #        method: delete
  #        cors: true

plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation
